### ISSUE TITLE
Icon disappears after install and never show up.

### ISSUE THREAD

**Issue by Techwolf** [denilsonsa/crx-reload-tab#6]
I install the extension, the icon pops up saying its installed, then disappears while the other extensions stay. This prevents the usage of this extension on web site as there is no way to force the icon to show back up.

Tried on chromium and brave browser.

Update: Found a workaround. On brave, click on the puzzle icon, move the mouse down to the extension and click on it.

**Comment by denilsonsa** [comment]
That sounds like normal behavior in recent versions of Chrome: https://ui.vision/blog/show-hide-chrome-extension-icon/

(I wish I could link to [official release notes](https://developers.google.com/web/updates/capabilities), but I couldn't find it.)
